// Generated by scripts/build_alpha_mission_delivery_v0_2.py
// Offline contract types only; do not import app runtime code here.

export type AlphaMissionType =
  | "context_dependence_test"
  | "boundary_test"
  | "bridge_test"
  | "archetype_depth_test"
  | "gateway_test"
  | "artist_depth_test"
  | "album_container_test"
  | "false_nearby_test"
  | "evidence_repair_test"
  | "exception_scope_test";

export type AppImportStatus =
  | "review_only"
  | "schema_valid"
  | "contract_valid"
  | "needs_revision"
  | "rejected_product"
  | "app_import_candidate"
  | "app_import_blocked_unresolved"
  | "app_import_blocked_policy"
  | "app_import_ready";

export type RouteItemRole =
  | "anchor"
  | "context"
  | "bridge"
  | "boundary"
  | "probe"
  | "comparator"
  | "control";

export type ResolutionStatus = "resolved" | "candidate" | "unresolved" | "blocked";

export interface AlphaMissionRouteItemV0_2 {
  mission_item_id: string;
  sequence_index: number;
  role: RouteItemRole;
  song_title: string;
  artist_name: string;
  album_title: string | null;
  canonical_song_id: string | null;
  canonical_artist_id: string | null;
  canonical_album_id: string | null;
  apple_music_id: string | null;
  apple_music_url: string | null;
  duration_ms: number;
  artwork_url: string | null;
  preview_url: string | null;
  resolution_status: ResolutionStatus;
  expected_signal: string;
  why_in_route: string;
  reaction_chip_set_id: string | null;
  risk_flags: string[];
  source_opportunity_id: string | null;
  source_mission_type: string | null;
  target_object_ids: string[];
  graph_context_refs: string[];
}

export interface AlphaAppImportMissionPayloadV0_2 {
  mission_id: string;
  contract_version: "alpha_mission_delivery_v0_2";
  app_import_status: AppImportStatus;
  mission_type: AlphaMissionType;
  mission_archetype:
    | "Nearby Road"
    | "Frontier Route"
    | "Dead End Check"
    | "Correction Route"
    | "Artist Route"
    | "Album Route"
    | "Memory Route"
    | "Start Here";
  title: string;
  brief: string;
  hypothesis: string;
  why_this_mission_now: string;
  coherence_sentence: string;
  risk_level: "low" | "medium" | "high";
  route: AlphaMissionRouteItemV0_2[];
  completion_criteria: Record<string, unknown>;
  feedback_model: Record<string, unknown>;
  source_trace: Record<string, unknown>;
  validation: Record<string, unknown>;
  resolution: Record<string, unknown>;
  runtime_flags: {
    runtime_selector_wiring: false;
    real_listener_evidence_connected: false;
    production_mission_generation_allowed: false;
    final_mission_content: false;
    canonical_graph_mutation_allowed: false;
  };
}
